import Providers from "./providers";
import "./globals.css";

import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import FooterPage from "./_components/footer/page";
import { DataCacheProvider } from "_contexts/DataCacheContext";
import HeaderPage from "./_components/header/page";

const fonte = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Casa de Carnes JP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={fonte.className + " bg-gray-100 dark:bg-gray-900 min-h-dvh flex flex-col justify-around"}>
        <Providers>
          <DataCacheProvider>
            <HeaderPage />
            {children}
            <FooterPage />
          </DataCacheProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
