import Providers from "./providers"
import "./globals.css"

import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const fonte = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Casa de Carnes JP",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  
}) {


  return (
    <html lang="pt-BR">
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
